spring.application.name=espectrum


spring.datasource.url=jdbc:postgresql://ep-steep-dew-ac30ceem-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_EzsIiV9Htf8T
spring.jpa.hibernate.ddl-auto=update

