spring.application.name=espectrum
invertexto.api.token = 26957|04jijGeI6xMg4pkxswPFLQvkDvZkXgLB

spring.datasource.url=jdbc:postgresql://ep-steep-dew-ac30ceem-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_EzsIiV9Htf8T
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=espectrumsuporte@gmail.com
spring.mail.password=nuwt crsr yiep iicw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

suporte.destinatarios = espectrumsuporte@gmail.com





